### ISSUE TITLE
Write doc for @query pipe syntax

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/Query.jl#120]

**Comment by ValdarT** [comment]
Probably not the best place for this but I wanted to raise this topic before the `@query` macro becomes more “official”.

As I understand, it was added only for syntax reasons? In my opinion it doesn’t really add much in that regard. For aesthetics and readability, I think one can’t really beat the `@query` syntax that was used the StructuredQueries.jl and Graft.jl packages:
```
@query iris |> 
    filter(sepal_length > 5.0) |> 
    select(twice_sepal_length = 2*sepal_length)
```
So perhaps it makes sense to use the same syntax in Query.jl as well if that is possible? It isn’t much of an issue but I think many people would really prefer such a distinct, concise, dplyr-like syntax. 
(Note that DataFramesMeta did the same – you can either use separate macros or one `@linq` macro to reduce the clutter from all the `@`.)

**Comment by davidanthoff** [comment]
Have you tried the standalone query commands? They are described in the experimental section of the docs. Any feedback on that would be welcome!

I agree, the ``@query`` thing is not very useful. I added it before I started working on the standalone commands. So right now it is a bridge between the LINQ style, and the pipe style query pattern. I don’t think it does much harm, so probably ok to just leave it?

**Comment by ValdarT** [comment]
Yes, the standalone macros work well for this kind of code style. 

But I have admit that I am not a fan of the syntax. For example this: `df |> @groupby(_.a) |> @map({a=_.key, b=mean(_..b)})`. It’s quite cluttered and one has to know 3 Query.jl specific things (`._`, `_..`, `{}`) to understand it whereas the StructuredQueries.jl syntax above (or dplyr’s) is clean and self-explanatory. This clean and nonesoteric syntax (in contrast to base R) is probably the main reason behind dplyr’s original popularity.
So, to someone spoiled by dplyr, the standalone macro approach works well and it is readable enough, it just doesn’t look as nice.

I personally don’t like the clutter from `@`-s themselves either but getting rid of that might not be worth it. DataFramesMeta.jl, as mentioned, offers both ways (the general `@linq` macro and a set of macros as in Query.jl).

By the way, in my opinion, the idea of `$` instead of `._` would definitely help.

**Comment by davidanthoff** [comment]
Yeah, I completely agree that it very quickly looks like special character soup. I have a couple of plans to improve on this:
1. Once 0.7 is out I have a way to get rid of the ``..`` syntax, so that it at least can just be a single ``.``
2. As you mentioned, the ``$`` would make things easier to read.
3. It probably makes sense to add another set of commands that makes working with tabular sources and sinks easier. The current commands entirely abstract from the tabular concept, i.e. they really bridge between tabular and other data structures. That makes them quite general, but of course the syntax for a pure table story is slightly more verbose. So I've been thinking for a while about another front-end that has more dplyr like syntax in that it wouldn't support arbitrary element types from sources and sinks, but would be limited to tables. The whole thing would be simply another front end (like we already have two front ends: the LINQ style and the standalone style), but would utilize the same backends that already exist. I'm mainly holding off from this right now because some of this can't be done with the current NamedTuples package, but will be super easy with the new NamedTuples in julia 0.7. I'm also still mulling options that would integrate this nicely into the existing standalone commands.

**Comment by ValdarT** [comment]
Makes sense. And hopefully the old dream of AbstractTable interface also finally comes together with Julia 0.7/1.0 and NamedTuples. That should just solve most of this.
