### ISSUE TITLE
Add a Project.toml to follow the procedure of developing package in Pkg mode. 

### ISSUE THREAD

**Issue by thautwarm** [queryverse/Query.jl#239]
Currently we cannot test the package locally in the following way.

```julia
pkg> activate .
Query.jl> test
```

**Comment by davidanthoff** [comment]
I don't want to add a ``Project.toml`` file at this point because it kind of screws up the CI testing: we need a REQUIRE file for the whole METADATA infrastructure. If we have a REQUIRE file and a Project.toml, then the CI and METADATA tests use the Project.toml file, and the REQUIRE file won't be tested. But then on users systems the REQUIRE file matters, and so we would essentially be shipping a pretty critical part that is not tested by any CI.

The way I work on this package is that I ``]dev`` it into some global environment, and then you can just call ``test Query`` in that environment.

**Comment by thautwarm** [comment]
okay, gotcha.
